=== vgambier/computer-database/persistence/src/test/resources/dataset.dtd
<!ELEMENT dataset (
    authorities*,
    users*,
    authority*,
    company*,
    computer*)>

<!ELEMENT authorities EMPTY>
<!ATTLIST authorities
    id CDATA #REQUIRED
    authority CDATA #REQUIRED
>

<!ELEMENT users EMPTY>
<!ATTLIST users
    id CDATA #REQUIRED
    username CDATA #REQUIRED
    password CDATA #REQUIRED
    enabled CDATA #IMPLIED
>

<!ELEMENT authority EMPTY>
<!ATTLIST authority
    user_id CDATA #REQUIRED
    authority_id CDATA #REQUIRED
>

<!ELEMENT company EMPTY>
<!ATTLIST company
    id CDATA #REQUIRED
    name CDATA #IMPLIED
>

<!ELEMENT computer EMPTY>
<!ATTLIST computer
    id CDATA #REQUIRED
    name CDATA #IMPLIED
    introduced CDATA #IMPLIED
    discontinued CDATA #IMPLIED
    company_id CDATA #IMPLIED
>

=== vgambier/computer-database/persistence/src/test/resources/dataset.xml
<!DOCTYPE dataset SYSTEM "src/test/resources/dataset.dtd">
<dataset>
    <company id="1" name="Company1"/>
    <company id="2" name="Company2"/>
    <company id="4" name="Company4"/>
    <company id="5" name="Company5"/>
    <company id="6" name="Thinking Machines"/>
    <company id="9" name="TestmAcTest"/>

    <computer id="1"
              name="Computer1"
              introduced="2010-10-10"
              discontinued="2010-10-12"
              company_id="1"/>
    <computer id="3"
              name="Computer3"
              introduced="1989-12-05"
              discontinued="2010-10-12" />
    <computer id="15"
              name="Computer15"
              introduced="1999-09-06"
              company_id="5"/>
    <computer id="18"
              name="Computer18"
              company_id="1"/>
    <computer id="22"
              name="Computer22"/>
    <computer id="42"
              name="Computer42"
              discontinued="2000-03-03"
              company_id="2"/>
    <computer id="44" name="Computer44"
              introduced="1970-01-01"
              discontinued="2070-01-01"
              company_id="4"/>
    <computer id="69"
              name="Macintosh"  />
    <computer id="666"
              name="Evil"
              introduced="2000-11-12"
              company_id="9" />
    <computer id="999"
              name="Computer999"
              introduced="1980-11-11"
              discontinued="2099-01-01"
              company_id="5"/>

    <users id="1"
           username="admin"
           password="$2a$10$ZXletnyPCSAPYxJqoW2vfuBfxQ8M.Td.aC8/jOEOyGlk5YotfgPmO"
           enabled="1"/>
    <users id="2"
           username="user"
           password="$2a$10$Oi0B8zq3qj7AWTsETTbP5eyVpcs5Bo0Y81.eNIu0pw/5laMmK95Wa"
           enabled="1"/>
    <users id="3"
           username="userDisable"
           password="$2a$10$Uz1rd1E3jvEthg29AufvL.9zlA5g/SUnErrGDBpf2AObxZtXWvXjG"
           enabled="0"/>
    <users id="4"
           username="userEnable"
           password="$2a$10$cIeVWdzweJ4h79nfE0VNzeeisiYTHYoAglyjgCXZW7b7bxkc718Am"
           enabled="1"/>

    <authorities id="1"
                 authority="ROLE_ADMIN"/>
    <authorities id="2"
                 authority="ROLE_USER"/>
    <authorities id="3"
                 authority="ROLE_TEST"/>

    <authority user_id="1"
               authority_id="1"/>
    <authority user_id="1"
               authority_id="2"/>
    <authority user_id="2"
               authority_id="2"/>
    <authority user_id="3"
               authority_id="2"/>
    <authority user_id="4"
               authority_id="2"/>

</dataset>

=== vgambier/computer-database/persistence/src/test/resources/ComputerDAOTest/testUpdateComputer.xml
<!DOCTYPE dataset SYSTEM "src/test/resources/dataset.dtd">
<dataset>

    <computer id="1"
              name="Computer1"
              introduced="2010-10-10"
              discontinued="2010-10-12"
              company_id="1"/>
    <computer id="3"
              name="Computer3"
              introduced="1989-12-05"
              discontinued="2010-10-12" />
    <computer id="15"
              name="Computer15"
              introduced="1999-09-06"
              company_id="5"/>
    <computer id="18"
              name="Computer18"
              company_id="1"/>
    <computer id="22"
              name="Computer22Improved"
              introduced="1989-05-09"
              discontinued="2019-01-02"
              company_id="1"/>
    <computer id="42"
              name="Computer42"
              discontinued="2000-03-03"
              company_id="2"/>
    <computer id="44" name="Computer44"
              introduced="1970-01-01"
              discontinued="2070-01-01"
              company_id="4"/>
    <computer id="69"
              name="Macintosh"  />
    <computer id="666"
              name="Evil"
              introduced="2000-11-12"
              company_id="9" />
    <computer id="999"
              name="Computer999"
              introduced="1980-11-11"
              discontinued="2099-01-01"
              company_id="5"/>

</dataset>
